maqueen.IR_callbackUser(function ({ myparam: message }) {
    basic.showString("" + message)
})
basic.forever(function () {
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CW, 100)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CW, 100)
    basic.pause(100)
    maqueen.motorStop(maqueen.aMotors.M1)
    maqueen.motorStop(maqueen.aMotors.M2)
    basic.pause(100)
    maqueen.MotorRun(maqueen.aMotors.M1, maqueen.Dir.CCW, 100)
    maqueen.MotorRun(maqueen.aMotors.M2, maqueen.Dir.CCW, 100)
    basic.pause(100)
    maqueen.motorStopAll()
    basic.pause(100)
    basic.showNumber(maqueen.sensor(PingUnit.Centimeters))
    basic.showString("" + maqueen.readPatrol(maqueen.Patrol.PatrolLeft))
    basic.showString("" + maqueen.readPatrol(maqueen.Patrol.PatrolRight))
    basic.showString("" + maqueen.IR_read())
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    basic.pause(100)
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOff)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOff)
    basic.pause(100)
})